camunda:
  client:
    mode: selfmanaged
    grpc-address: http://localhost:26500
    rest-address: http://localhost:8088
    prefer-rest-over-grpc: false
    auth:
      method: none
server:
  port: 8099